//
//  CPMLEncryptionRequest.swift
//  
//
//  Created by Evan Anderson on 8/3/23.
//

import Foundation

public extension ClientPacketMojang.Login {
    struct EncryptionRequest : ClientPacketMojangProtocol {
        /// Appears to be empty.
        let server_id:String
        /// Length of Public Key
        let public_key_length:Int
        /// The server's public key, in bytes.
        let public_key:[UInt8]
        /// Length of Verify Token. Always 4 for Notchian servers.
        let verify_token_length:Int
        /// A sequence of random bytes generated by the server.
        let verify_token:[UInt8]
    }
}
